# ============================= actuator监控 ============================= #
management:
  server:
    port: 1234           # 管理的端口调整成1234
    address: 127.0.0.1   # 只允许127.0.0.1访问
    servlet:
      context-path: /monitor  # actuator的访问路径
  endpoint:
    shutdown:
      enabled: true    # 启用shutdown功能
    beans.cache.time-to-live: 10s
    env.enabled: true  # 启用端点 env
  endpoints:
    enabled-by-default: true # 设置端点是否可用 默认只有shutdown可用
    web:
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # include: env   # 方式1: 暴露端点 env 配置多个,隔开
        include: "*"     # 方式2: 包括所有端点, 注意需要添加引号
        # 排除端点
        exclude: shutdown

jasypt:
  encryptor:
    property:
      prefix: "ENC@["
      suffix: "]"
